server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: carro-service
  datasource:
    url: jdbc:h2:file:./data/carrosdb;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}